### ISSUE TITLE
Complete Descriptors Of Warden Political Focus Tree

### ISSUE THREAD

**Issue by RegaSaurus24** [SafeHouse-Studios/Foxhole-Conquest#33]
**IN ORDER TO COMPLETE THIS TASK:** Design document of the Warden political focus tree must first be completed.
[Warden Focus Tree Design Document](https://docs.google.com/document/d/1nBrQorOAaVDKdAS-1GCK_uGADRjIHWgAxXIBYLZnBMk/edit?usp=sharing)

**IN ORDER TO COMPLETE THIS TASK:** Issue #32  must be completed.

**Task Details:** Add descriptors to all Warden political focuses from the documentation, check for spelling and grammar errors as you go. Specifically the political section is the center section of the focus tree. Your job is to go through the focus document for the Warden Nation and ensure that all of the focuses within this central section all have the correct descriptions as is listed in the "Full Warden Focus Tree Designs". You will as mentioned also proof read as you go for spelling and grammar errors and fix them as you go, although be careful not to over wright anything that could be a lore name rather than a misspelling, if unsure ask design leader.

**Documentation:** [Full Warden Focus Tree Designs](https://docs.google.com/document/d/1SKl4GcNm26qxHmSv5CZwRSjYSlV2vQap/edit)
[Layout Designs Of Full Warden Focus Tree](https://drive.google.com/file/d/13g094-fFBCz2B4QAgWp8MCZZXAoD28tB/view?usp=sharing)

**Tutorial:** [Basic Focus Tree Creation](https://www.youtube.com/watch?v=svFVLXzU2MQ&ab_channel=TheIronWorkshop)

**Comment by LegendGman** [comment]
The Labor Party & United Workers of Caovia: Have same description
