### ISSUE TITLE
Complete Temporary GFX Shine Of Warden Political Focus Tree

### ISSUE THREAD

**Issue by RegaSaurus24** [SafeHouse-Studios/Foxhole-Conquest#36]
**IN ORDER TO COMPLETE THIS TASK:** Issue #35 must be completed.

**Task Details:** This task involved completing the shine effects for all of the temporary icons assigned to the Warden political focus tree. The political tree is the tree in the center of the "Layout Designs Of Full Warden Focus Tree" document.

**Documentation:** [Layout Designs Of Full Warden Focus Tree](https://drive.google.com/file/d/13g094-fFBCz2B4QAgWp8MCZZXAoD28tB/view?usp=sharing)

**Tutorial:** [Basic Focus Tree Creation](https://www.youtube.com/watch?v=svFVLXzU2MQ&ab_channel=TheIronWorkshop)

**Comment by LegendGman** [comment]
Needs to be verified in-game

**Comment by RegaSaurus24** [comment]
This issue is no longer required as art have completed the main focus icons.
