### ISSUE TITLE
Complete Descriptors Of Colonial Naval Focus Tree

### ISSUE THREAD

**Issue by RegaSaurus24** [SafeHouse-Studios/Foxhole-Conquest#78]
**IN ORDER TO COMPLETE THIS TASK:** Design document of the Colonial naval focus tree must first be completed.
[Colonial Focus Tree Design Document](https://docs.google.com/document/d/1EuS-yvnH6l1r-l45CPTbGUQa5oUczuc__1L51WUL0C8/edit?usp=sharing)

**IN ORDER TO COMPLETE THIS TASK:** Issue #77 must be completed.

**Task Details:** Add descriptors to all Colonial naval focuses from the documentation, check for spelling and grammar errors as you go. Specifically the naval section is the far right hand section of the focus tree. Your job is to go through the focus document for the Colonial Nation and ensure that all of the focuses within this far right hand section all have the correct descriptions as is listed in the "Full Colonial Focus Tree Designs". You will as mentioned also proof read as you go for spelling and grammar errors and fix them as you go, although be careful not to over wright anything that could be a lore name rather than a misspelling, if unsure ask design leader.

**Documentation:** [Full Colonial Focus Tree Designs](https://docs.google.com/document/d/1EuS-yvnH6l1r-l45CPTbGUQa5oUczuc__1L51WUL0C8/edit?usp=sharing)
[Layout Designs Of Full Colonial Focus Tree](https://drive.google.com/file/d/1Ub7985haNfphJt16pfki2XhCCatnBh32/view?usp=sharing)

**Tutorial:** [Basic Focus Tree Creation](https://www.youtube.com/watch?v=svFVLXzU2MQ&ab_channel=TheIronWorkshop)

**Comment by hamsnadwich** [comment]
Finished all descriptors, closing
