### ISSUE TITLE
Complete Main GFX Of Colonial Naval Focus Tree

### ISSUE THREAD

**Issue by RegaSaurus24** [SafeHouse-Studios/Foxhole-Conquest#80]
[**IN ORDER TO COMPLETE THIS TASK:** Issue #77 must be completed.

**IN ORDER TO COMPLETE THIS TASK:** Custom focus icons for all of the Colonial naval tree will need to have been created.

**Task Details:** This task involved uploading the appropriate GFX from the our own libraries and assigning them to their focuses. The icons can be found at "Main Colonial Focus Icons" and the method of attaching them can be found in the tutorial video. The naval tree is the tree in the far right hand side of the "Layout Designs Of Full Colonial Focus Tree" document.

**Documentation:** [Layout Designs Of Full Colonial Focus Tree](https://drive.google.com/file/d/1Ub7985haNfphJt16pfki2XhCCatnBh32/view?usp=sharing)
[Colonial Naval Focus Icons](https://drive.google.com/drive/folders/1KI2_H3RcwM0U8FMTbsSlCxiICfD_x3CW?usp=sharing)

**Tutorial:** [Basic Focus Tree Creation](https://www.youtube.com/watch?v=svFVLXzU2MQ&ab_channel=TheIronWorkshop)](https://github.com/SafeHouse-Studios/Foxhole-Conquest/issues/53#:~:text=Skip%20to%20content,About)

**Comment by hamsnadwich** [comment]
All gfx added as suggested
