### ISSUE TITLE
Complete Main GFX Shine Of Colonial Naval Focus Tree

### ISSUE THREAD

**Issue by RegaSaurus24** [SafeHouse-Studios/Foxhole-Conquest#81]
**IN ORDER TO COMPLETE THIS TASK:** Issue #80 must be completed.

**Task Details:** This task involved completing the shine effects for all of the main icons assigned to the Colonial naval focus tree. The naval tree is the tree in the far right side of the "Layout Designs Of Full Colonial Focus Tree" document.

**Documentation:** [Layout Designs Of Full Colonial Focus Tree](https://drive.google.com/file/d/1Ub7985haNfphJt16pfki2XhCCatnBh32/view?usp=sharing)

**Tutorial:** [Basic Focus Tree Creation](https://www.youtube.com/watch?v=svFVLXzU2MQ&ab_channel=TheIronWorkshop)

**Comment by hamsnadwich** [comment]
shine added following tutorial
